=== PolpOnline/presenze-meucci/src/backend/src/fixtures/lessons/orario/Orario Provvisorio 5 ore  v5-XML/classi.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:choice maxOccurs="unbounded">
<xsd:element ref="classi"/>
</xsd:choice>
</xsd:complexType>
</xsd:element>
<xsd:element name="classi">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="idclasse" index-key="idclasse" primary="yes" unique="yes" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="idclasse" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="nomeclasse" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="nomebreveclasse" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== PolpOnline/presenze-meucci/src/backend/src/fixtures/lessons/orario/Orario Provvisorio 5 ore  v5-XML/classi.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="classi.xsd">
<classi>
<idclasse>C0000</idclasse>
<nomeclasse>1^ATL</nomeclasse>
<nomebreveclasse>1^ATL</nomebreveclasse>
</classi>
<classi>
<idclasse>C0050</idclasse>
<nomeclasse>1^ATL alt</nomeclasse>
<nomebreveclasse>1^ATL alt</nomebreveclasse>
</classi>
<classi>
<idclasse>C0051</idclasse>
<nomeclasse>1^ATL rel</nomeclasse>
<nomebreveclasse>1^ATL rel</nomebreveclasse>
</classi>
<classi>
<idclasse>C0052</idclasse>
<nomeclasse>1^ATL studio</nomeclasse>
<nomebreveclasse>1^ATL studio</nomebreveclasse>
</classi>
<classi>
<idclasse>C0001</idclasse>
<nomeclasse>1^BMME</nomeclasse>
<nomebreveclasse>1^BMME</nomebreveclasse>
</classi>
<classi>
<idclasse>C0053</idclasse>
<nomeclasse>1^BMME alt</nomeclasse>
<nomebreveclasse>1^BMME alt</nomebreveclasse>
</classi>
<classi>
<idclasse>C0054</idclasse>
<nomeclasse>1^BMME rel</nomeclasse>
<nomebreveclasse>1^BMME rel</nomebreveclasse>
</classi>
<classi>
<idclasse>C0055</idclasse>
<nomeclasse>1^BMME studio</nomeclasse>
<nomebreveclasse>1^BMME studio</nomebreveclasse>
</classi>
<classi>
<idclasse>C0002</idclasse>
<nomeclasse>1^CMME</nomeclasse>
<nomebreveclasse>1^CMME</nomebreveclasse>
</classi>
<classi>
<idclasse>C0056</idclasse>
<nomeclasse>1^CMME alt</nomeclasse>
<nomebreveclasse>1^CMME alt</nomebreveclasse>
</classi>
<classi>
<idclasse>C0057</idclasse>
<nomeclasse>1^CMME rel</nomeclasse>
<nomebreveclasse>1^CMME rel</nomebreveclasse>
</classi>
<classi>
<idclasse>C0058</idclasse>
<nomeclasse>1^CMME studio</nomeclasse>
<nomebreveclasse>1^CMME studio</nomebreveclasse>
</classi>
<classi>
<idclasse>C0003</idclasse>
<nomeclasse>1^DMME</nomeclasse>
<nomebreveclasse>1^DMME</nomebreveclasse>
</classi>
<classi>
<idclasse>C0059</idclasse>
<nomeclasse>1^DMME alt</nomeclasse>
<nomebreveclasse>1^DMME alt</nomebreveclasse>
</classi>
<classi>
<idclasse>C0060</idclasse>
<nomeclasse>1^DMME rel</nomeclasse>
<nomebreveclasse>1^DMME rel</nomebreveclasse>
</classi>
<classi>
<idclasse>C0061</idclasse>
<nomeclasse>1^DMME studio</nomeclasse>
<nomebreveclasse>1^DMME studio</nomebreveclasse>
</classi>
<classi>
<idclasse>C0004</idclasse>
<nomeclasse>1^EIT</nomeclasse>
<nomebreveclasse>1^EIT</nomebreveclasse>
</classi>
<classi>
<idclasse>C0005</idclasse>
<nomeclasse>1^FIT</nomeclasse>
<nomebreveclasse>1^FIT</nomebreveclasse>
</classi>
<classi>
<idclasse>C0062</idclasse>
<nomeclasse>1^FIT alt</nomeclasse>
<nomebreveclasse>1^FIT alt</nomebreveclasse>
</classi>
<classi>
<idclasse>C0063</idclasse>
<nomeclasse>1^FIT rel</nomeclasse>
<nomebreveclasse>1^FIT rel</nomebreveclasse>
</classi>
<classi>
<idclasse>C0064</idclasse>
<nomeclasse>1^FIT studio</nomeclasse>
<nomebreveclasse>1^FIT studio</nomebreveclasse>
</classi>
<classi>
<idclasse>C0006</idclasse>
<nomeclasse>1^GIT</nomeclasse>
<nomebreveclasse>1^GIT</nomebreveclasse>
</classi>
<classi>
<idclasse>C0065</idclasse>
<nomeclasse>1^GIT alt</nomeclasse>
<nomebreveclasse>1^GIT alt</nomebreveclasse>
</classi>
<classi>
<idclasse>C0066</idclasse>
<nomeclasse>1^GIT rel</nomeclasse>
<nomebreveclasse>1^GIT rel</nomebreveclasse>
</classi>
<classi>
<idclasse>C0067</idclasse>
<nomeclasse>1^GIT studio</nomeclasse>
<nomebreveclasse>1^GIT studio</nomebreveclasse>
</classi>
<classi>
<idclasse>C0007</idclasse>
<nomeclasse>1^HIT</nomeclasse>
<nomebreveclasse>1^HIT</nomebreveclasse>
</classi>
<classi>
<idclasse>C0068</idclasse>
<nomeclasse>1^HIT alt</nomeclasse>
<nomebreveclasse>1^HIT alt</nomebreveclasse>
</classi>
<classi>
<idclasse>C0069</idclasse>
<nomeclasse>1^HIT rel</nomeclasse>
<nomebreveclasse>1^HIT rel</nomebreveclasse>
</classi>
<classi>
<idclasse>C0070</idclasse>
<nomeclasse>1^HIT studio</nomeclasse>
<nomebreveclasse>1^HIT studio</nomebreveclasse>
</classi>
<classi>
<idclasse>C0008</idclasse>
<nomeclasse>1^IIT</nomeclasse>
<nomebreveclasse>1^IIT</nomebreveclasse>
</classi>
<classi>
<idclasse>C0071</idclasse>
<nomeclasse>1^IIT rel</nomeclasse>
<nomebreveclasse>1^IIT rel</nomebreveclasse>
</classi>
<classi>
<idclasse>C0072</idclasse>
<nomeclasse>1^IIT studio</nomeclasse>
<nomebreveclasse>1^IIT studio</nomebreveclasse>
</classi>
<classi>
<idclasse>C0009</idclasse>
<nomeclasse>1^LEE</nomeclasse>
<nomebreveclasse>1^LEE</nomebreveclasse>
</classi>
<classi>
<idclasse>C0073</idclasse>
<nomeclasse>1^LEE alt</nomeclasse>
<nomebreveclasse>1^LEE alt</nomebreveclasse>
</classi>
<classi>
<idclasse>C0074</idclasse>
<nomeclasse>1^LEE rel</nomeclasse>
<nomebreveclasse>1^LEE rel</nomebreveclasse>
</classi>
<classi>
<idclasse>C0075</idclasse>
<nomeclasse>1^LEE studio</nomeclasse>
<nomebreveclasse>1^LEE studio</nomebreveclasse>
</classi>
<classi>
<idclasse>C0010</idclasse>
<nomeclasse>1^MEE</nomeclasse>
<nomebreveclasse>1^MEE</nomebreveclasse>
</classi>
<classi>
<idclasse>C0076</idclasse>
<nomeclasse>1^MEE alt</nomeclasse>
<nomebreveclasse>1^MEE alt</nomebreveclasse>
</classi>
<classi>
<idclasse>C0077</idclasse>
<nomeclasse>1^MEE rel</nomeclasse>
<nomebreveclasse>1^MEE rel</nomebreveclasse>
</classi>
<classi>
<idclasse>C0078</idclasse>
<nomeclasse>1^MEE studio</nomeclasse>
<nomebreveclasse>1^MEE studio</nomebreveclasse>
</classi>
<classi>
<idclasse>C0011</idclasse>
<nomeclasse>2^ATL</nomeclasse>
<nomebreveclasse>2^ATL</nomebreveclasse>
</classi>
<classi>
<idclasse>C0079</idclasse>
<nomeclasse>2^ATL alt</nomeclasse>
<nomebreveclasse>2^ATL alt</nomebreveclasse>
</classi>
<classi>
<idclasse>C0080</idclasse>
<nomeclasse>2^ATL rel</nomeclasse>
<nomebreveclasse>2^ATL rel</nomebreveclasse>
</classi>
<classi>
<idclasse>C0081</idclasse>
<nomeclasse>2^ATL studio</nomeclasse>
<nomebreveclasse>2^ATL studio</nomebreveclasse>
</classi>
<classi>
<idclasse>C0012</idclasse>
<nomeclasse>2^BMME</nomeclasse>
<nomebreveclasse>2^BMME</nomebreveclasse>
</classi>
<classi>
<idclasse>C0082</idclasse>
<nomeclasse>2^BMME rel</nomeclasse>
<nomebreveclasse>2^BMME rel</nomebreveclasse>
</classi>
<classi>
<idclasse>C0083</idclasse>
<nomeclasse>2^BMME studio</nomeclasse>
<nomebreveclasse>2^BMME studio</nomebreveclasse>
</classi>
<classi>
<idclasse>C0013</idclasse>
<nomeclasse>2^CMME</nomeclasse>
<nomebreveclasse>2^CMME</nomebreveclasse>
</classi>
<classi>
<idclasse>C0084</idclasse>
<nomeclasse>2^DMM rel</nomeclasse>
<nomebreveclasse>2^DMM rel</nomebreveclasse>
</classi>
<classi>
<idclasse>C0085</idclasse>
<nomeclasse>2^DMM studio</nomeclasse>
<nomebreveclasse>2^DMM studio</nomebreveclasse>
</classi>
<classi>
<idclasse>C0014</idclasse>
<nomeclasse>2^DMME</nomeclasse>
<nomebreveclasse>2^DMME</nomebreveclasse>
</classi>
<classi>
<idclasse>C0015</idclasse>
<nomeclasse>2^EIT</nomeclasse>
<nomebreveclasse>2^EIT</nomebreveclasse>
</classi>
<classi>
<idclasse>C0086</idclasse>
<nomeclasse>2^EIT rel</nomeclasse>
<nomebreveclasse>2^EIT rel</nomebreveclasse>
</classi>
<classi>
<idclasse>C0087</idclasse>
<nomeclasse>2^EIT studio</nomeclasse>
<nomebreveclasse>2^EIT studio</nomebreveclasse>
</classi>
<classi>
<idclasse>C0016</idclasse>
<nomeclasse>2^FIT</nomeclasse>
<nomebreveclasse>2^FIT</nomebreveclasse>
</classi>
<classi>
<idclasse>C0088</idclasse>
<nomeclasse>2^FIT rel</nomeclasse>
<nomebreveclasse>2^FIT rel</nomebreveclasse>
</classi>
<classi>
<idclasse>C0089</idclasse>
<nomeclasse>2^FIT studio</nomeclasse>
<nomebreveclasse>2^FIT studio</nomebreveclasse>
</classi>
<classi>
<idclasse>C0017</idclasse>
<nomeclasse>2^GIT</nomeclasse>
<nomebreveclasse>2^GIT</nomebreveclasse>
</classi>
<classi>
<idclasse>C0090</idclasse>
<nomeclasse>2^GIT rel</nomeclasse>
<nomebreveclasse>2^GIT rel</nomebreveclasse>
</classi>
<classi>
<idclasse>C0091</idclasse>
<nomeclasse>2^GIT studio</nomeclasse>
<nomebreveclasse>2^GIT studio</nomebreveclasse>
</classi>
<classi>
<idclasse>C0092</idclasse>
<nomeclasse>2^HEE studio</nomeclasse>
<nomebreveclasse>2^HEE studio</nomebreveclasse>
</classi>
<classi>
<idclasse>C0093</idclasse>
<nomeclasse>2^IEE studio</nomeclasse>
<nomebreveclasse>2^IEE studio</nomebreveclasse>
</classi>
<classi>
<idclasse>C0018</idclasse>
<nomeclasse>2^IIT</nomeclasse>
<nomebreveclasse>2^IIT</nomebreveclasse>
</classi>
<classi>
<idclasse>C0094</idclasse>
<nomeclasse>2^IIT rel</nomeclasse>
<nomebreveclasse>2^IIT rel</nomebreveclasse>
</classi>
<classi>
<idclasse>C0019</idclasse>
<nomeclasse>2^LEE</nomeclasse>
<nomebreveclasse>2^LEE</nomebreveclasse>
</classi>
<classi>
<idclasse>C0095</idclasse>
<nomeclasse>2^LEE rel</nomeclasse>
<nomebreveclasse>2^LEE rel</nomebreveclasse>
</classi>
<classi>
<idclasse>C0020</idclasse>
<nomeclasse>2^MEE</nomeclasse>
<nomebreveclasse>Nuova classe (1)</nomebreveclasse>
</classi>
<classi>
<idclasse>C0021</idclasse>
<nomeclasse>2^NEE</nomeclasse>
<nomebreveclasse>Nuova classe (1)</nomebreveclasse>
</classi>
<classi>
<idclasse>C0022</idclasse>
<nomeclasse>3^A-AT</nomeclasse>
<nomebreveclasse>3^A-AT</nomebreveclasse>
</classi>
<classi>
<idclasse>C0096</idclasse>
<nomeclasse>3^A-AT rel</nomeclasse>
<nomebreveclasse>3^A-AT rel</nomebreveclasse>
</classi>
<classi>
<idclasse>C0097</idclasse>
<nomeclasse>3^A-AT studio</nomeclasse>
<nomebreveclasse>3^A-AT studio</nomebreveclasse>
</classi>
<classi>
<idclasse>C0023</idclasse>
<nomeclasse>3^A-IA</nomeclasse>
<nomebreveclasse>3^A-IA</nomebreveclasse>
</classi>
<classi>
<idclasse>C0024</idclasse>
<nomeclasse>3^A-LG</nomeclasse>
<nomebreveclasse>3^A-LG</nomebreveclasse>
</classi>
<classi>
<idclasse>C0025</idclasse>
<nomeclasse>3^A-MM</nomeclasse>
<nomebreveclasse>3^A-MM</nomebreveclasse>
</classi>
<classi>
<idclasse>C0098</idclasse>
<nomeclasse>3^AEC</nomeclasse>
<nomebreveclasse>3^AEC</nomebreveclasse>
</classi>
<classi>
<idclasse>C0026</idclasse>
<nomeclasse>3^AEC-AET</nomeclasse>
<nomebreveclasse>3^ECET</nomebreveclasse>
</classi>
<classi>
<idclasse>C0099</idclasse>
<nomeclasse>3^AET</nomeclasse>
<nomebreveclasse>3^AET</nomebreveclasse>
</classi>
<classi>
<idclasse>C0027</idclasse>
<nomeclasse>3^B-IA</nomeclasse>
<nomebreveclasse>3^B-IA</nomebreveclasse>
</classi>
<classi>
