=== PolpOnline/presenze-meucci/src/backend/src/fixtures/lessons/orario/Orario Provvisorio 5 ore  v5-XML/docenti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:choice maxOccurs="unbounded">
<xsd:element ref="docenti"/>
</xsd:choice>
</xsd:complexType>
</xsd:element>
<xsd:element name="docenti">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="iddocente" index-key="iddocente" primary="yes" unique="yes" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="iddocente" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="nomedocente" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="nomebrevedocente" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="emaildocente" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== PolpOnline/presenze-meucci/src/backend/src/fixtures/lessons/orario/Orario Provvisorio 5 ore  v5-XML/docenti.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="docenti.xsd">
<docenti>
<iddocente>P0000</iddocente>
<nomedocente>A012</nomedocente>
<nomebrevedocente>SODI NICCOLO'</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0001</iddocente>
<nomedocente>A012_ECC</nomedocente>
<nomebrevedocente>Nuovo docente (1)</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0002</iddocente>
<nomedocente>A033</nomedocente>
<nomebrevedocente>Nuovo docente (1)</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0003</iddocente>
<nomedocente>A040_supp</nomedocente>
<nomebrevedocente>A040_supp</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0004</iddocente>
<nomedocente>A041_2</nomedocente>
<nomebrevedocente>Nuovo docente (1)</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0005</iddocente>
<nomedocente>A041_ECC</nomedocente>
<nomebrevedocente>Nuovo docente (1)</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0006</iddocente>
<nomedocente>A042_ECC</nomedocente>
<nomebrevedocente>Nuovo docente (1)</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0007</iddocente>
<nomedocente>ACCORDINO FRANCESCO</nomedocente>
<nomebrevedocente>ACCORDINO FRANCESCO</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0008</iddocente>
<nomedocente>AGRELLO GIUSEPPINA</nomedocente>
<nomebrevedocente>AGRELLO GIUSEPPINA</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0009</iddocente>
<nomedocente>ALBANESI ANTONELLA</nomedocente>
<nomebrevedocente>ALBANESI ANTONELLA</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0010</iddocente>
<nomedocente>ANEDDA VALERIA</nomedocente>
<nomebrevedocente>ANEDDA VALERIA</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0011</iddocente>
<nomedocente>ANTONELLI ANDREA</nomedocente>
<nomebrevedocente>Nuovo docente (1)</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0012</iddocente>
<nomedocente>B016-COE</nomedocente>
<nomebrevedocente>B016-COE</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0013</iddocente>
<nomedocente>B017_ECC</nomedocente>
<nomebrevedocente>Nuovo docente (1)</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0014</iddocente>
<nomedocente>B09_ECC</nomedocente>
<nomebrevedocente>Nuovo docente (1)</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0015</iddocente>
<nomedocente>BAGNOLI FRANCESCA</nomedocente>
<nomebrevedocente>BAGNOLI FRANCESCA</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0016</iddocente>
<nomedocente>BALDI MARIA CRISTINA</nomedocente>
<nomebrevedocente>BALDI MARIA CRISTINA</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0017</iddocente>
<nomedocente>BARTOLI ANTONELLA</nomedocente>
<nomebrevedocente>A034</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0018</iddocente>
<nomedocente>BENVENUTI CLAUDIO</nomedocente>
<nomebrevedocente>BENVENUTI CLAUDIO</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0019</iddocente>
<nomedocente>BERTOLI FRANCESCO</nomedocente>
<nomebrevedocente>BERTOLI FRANCESCO</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0020</iddocente>
<nomedocente>BINI MICHELA</nomedocente>
<nomebrevedocente>BINI MICHELA</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0021</iddocente>
<nomedocente>BOCCINI VALENTINA</nomedocente>
<nomebrevedocente>BOCCINI VALENTINA</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0022</iddocente>
<nomedocente>BONDI FRANCESCO</nomedocente>
<nomebrevedocente>BONDI</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0023</iddocente>
<nomedocente>BONFIGLIOLI ROBERTO</nomedocente>
<nomebrevedocente>BONFIGLIOLI ROBERTO</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0024</iddocente>
<nomedocente>BORTOLINI GIANCARLO</nomedocente>
<nomebrevedocente>BORTOLINI GIANCARLO</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0025</iddocente>
<nomedocente>BROGI BARBARA</nomedocente>
<nomebrevedocente>BROGI BARBARA</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0026</iddocente>
<nomedocente>BRUNI ELISABETTA</nomedocente>
<nomebrevedocente>BRUNI ELISABETTA</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0027</iddocente>
<nomedocente>BRUNI VALENTINO</nomedocente>
<nomebrevedocente>BRUNI VALENTINO</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0028</iddocente>
<nomedocente>CANNAVO' PATRIZIA</nomedocente>
<nomebrevedocente>CANNAVO' PATRIZIA</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0029</iddocente>
<nomedocente>CAPARROTTA STEFANIA</nomedocente>
<nomebrevedocente>CAPARROTTA STEFANIA</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0030</iddocente>
<nomedocente>CAPEZIO FRANCESCO</nomedocente>
<nomebrevedocente>CAPEZIO FRANCESCO</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0031</iddocente>
<nomedocente>CAPPELLETTI LEONARDO</nomedocente>
<nomebrevedocente>CAPPELLETTI LEONARDO</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0032</iddocente>
<nomedocente>CARBONE CHRISTIAN</nomedocente>
<nomebrevedocente>Nuovo docente (1)</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0033</iddocente>
<nomedocente>CAUTIERO SALVATORE</nomedocente>
<nomebrevedocente>CAUTIERO SALVATORE</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0034</iddocente>
<nomedocente>CENCETTI ALICE</nomedocente>
<nomebrevedocente>CENCETTI ALICE</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0035</iddocente>
<nomedocente>CIANDELLA ALESSANDRO</nomedocente>
<nomebrevedocente>CIANDELLA ALESSANDRO</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0036</iddocente>
<nomedocente>CIARAMELLA SIMONA</nomedocente>
<nomebrevedocente>CIARAMELLA SIMONA</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0037</iddocente>
<nomedocente>COE_FERRARIS_EMPOLI</nomedocente>
<nomebrevedocente>Nuovo docente (1)</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0038</iddocente>
<nomedocente>CONTICELLI SIMONA</nomedocente>
<nomebrevedocente>CONTICELLI SIMONA</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0039</iddocente>
<nomedocente>CORRADO FEDERICO</nomedocente>
<nomebrevedocente>CORRADO FEDERICO</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0040</iddocente>
<nomedocente>CORSARO GIUSEPPE</nomedocente>
<nomebrevedocente>CORSARO GIUSEPPE</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0041</iddocente>
<nomedocente>COSTANZO ILARIA</nomedocente>
<nomebrevedocente>COSTANZO ILARIA</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0042</iddocente>
<nomedocente>CURRO' ROSALBA</nomedocente>
<nomebrevedocente>CURRO' ROSALBA</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0043</iddocente>
<nomedocente>DALLAI NADA</nomedocente>
<nomebrevedocente>DALLAI NADA</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0044</iddocente>
<nomedocente>DE LUCA GIUSTINA</nomedocente>
<nomebrevedocente>DE LUCA GIUSTINA</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0045</iddocente>
<nomedocente>DE MARIA - COE GALILEI</nomedocente>
<nomebrevedocente>COE GALILEI - ing</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0046</iddocente>
<nomedocente>DI FRUSCIA SABINA</nomedocente>
<nomebrevedocente>DI FRUSCIA SABINA</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0047</iddocente>
<nomedocente>DIMITRI ENRICO</nomedocente>
<nomebrevedocente>DIMITRI ENRICO</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0048</iddocente>
<nomedocente>ESPOSTO VALERIA</nomedocente>
<nomebrevedocente>ESPOSTO VALERIA</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0049</iddocente>
<nomedocente>FABBRI RAFFAELLA</nomedocente>
<nomebrevedocente>FABBRI RAFFAELLA</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0050</iddocente>
<nomedocente>FAGGIONI MARIA GABRIELLA</nomedocente>
<nomebrevedocente>FAGGIONI MARIA GABRIELLA</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0051</iddocente>
<nomedocente>FALCO ROBERTO</nomedocente>
<nomebrevedocente>Nuovo docente (1)</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0052</iddocente>
<nomedocente>FATUCCHI IVAN</nomedocente>
<nomebrevedocente>FATUCCHI IVAN</nomebrevedocente>
<emaildocente>(null)</emaildocente>
</docenti>
<docenti>
<iddocente>P0053</iddocente>
<nomedocente>FEDELE DELIA</nomedocente>
