=== PolpOnline/presenze-meucci/src/backend/src/fixtures/lessons/orario/Orario Provvisorio 5 ore  v5-XML/istanzeaule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:choice maxOccurs="unbounded">
<xsd:element ref="istanzeaule"/>
</xsd:choice>
</xsd:complexType>
</xsd:element>
<xsd:element name="istanzeaule">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="idfoglio idaula idistanzaaula" primary="yes" unique="yes" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="idfoglio" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="idaula" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="idistanzaaula" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="nomeistanzaaula" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== PolpOnline/presenze-meucci/src/backend/src/fixtures/lessons/orario/Orario Provvisorio 5 ore  v5-XML/istanzeaule.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="istanzeaule.xsd">
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0000</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-01</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0001</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-02</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0002</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-03</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0003</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-04</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0004</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-05</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0005</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-06</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0006</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-07</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0007</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-08</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0008</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-09</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0009</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-10</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0010</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-11</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0011</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-12</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0012</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-13</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0013</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-14</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0014</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-15</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0015</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-16</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0016</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-17</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0017</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-18</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0018</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-19</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0019</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-20</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0020</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-21</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0021</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-22</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0022</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-23</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0023</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-24</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0024</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-25</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0025</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-26</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0026</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-27</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0027</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-28</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0028</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-29</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0029</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-30</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0030</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-31</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0031</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-32</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0032</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-33</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0033</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-34</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0034</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-35</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0035</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-36</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0036</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-37</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0037</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-38</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0038</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-39</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0039</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-40</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0040</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-41</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0041</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-42</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0042</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-43</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0043</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-44</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0044</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-45</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0065</idaula>
<idistanzaaula>I0045</idistanzaaula>
<nomeistanzaaula>DISPOSIZIONE-46</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0086</idaula>
<idistanzaaula>I0000</idistanzaaula>
<nomeistanzaaula>ON LINE-01</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0086</idaula>
<idistanzaaula>I0001</idistanzaaula>
<nomeistanzaaula>ONLINE-02</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0086</idaula>
<idistanzaaula>I0002</idistanzaaula>
<nomeistanzaaula>ONLINE-03</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0086</idaula>
<idistanzaaula>I0003</idistanzaaula>
<nomeistanzaaula>ONLINE-04</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0086</idaula>
<idistanzaaula>I0004</idistanzaaula>
<nomeistanzaaula>ONLINE-05</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0086</idaula>
<idistanzaaula>I0005</idistanzaaula>
<nomeistanzaaula>ONLINE-06</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0086</idaula>
<idistanzaaula>I0006</idistanzaaula>
<nomeistanzaaula>ONLINE-07</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0086</idaula>
<idistanzaaula>I0007</idistanzaaula>
<nomeistanzaaula>ONLINE-08</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0086</idaula>
<idistanzaaula>I0008</idistanzaaula>
<nomeistanzaaula>ONLINE-09</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0086</idaula>
<idistanzaaula>I0009</idistanzaaula>
<nomeistanzaaula>ONLINE-10</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0086</idaula>
<idistanzaaula>I0010</idistanzaaula>
<nomeistanzaaula>ON LINE-11</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0086</idaula>
<idistanzaaula>I0011</idistanzaaula>
<nomeistanzaaula>ON LINE-12</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
<idfoglio>F0000</idfoglio>
<idaula>A0086</idaula>
<idistanzaaula>I0012</idistanzaaula>
<nomeistanzaaula>ON LINE-13</nomeistanzaaula>
</istanzeaule>
<istanzeaule>
