=== PolpOnline/presenze-meucci/src/backend/src/fixtures/lessons/orario/Orario Provvisorio 5 ore  v5-XML/materie.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:choice maxOccurs="unbounded">
<xsd:element ref="materie"/>
</xsd:choice>
</xsd:complexType>
</xsd:element>
<xsd:element name="materie">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="idmateria" index-key="idmateria" primary="yes" unique="yes" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="idmateria" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="nomemateria" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="nomebrevemateria" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="codicemiur" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== PolpOnline/presenze-meucci/src/backend/src/fixtures/lessons/orario/Orario Provvisorio 5 ore  v5-XML/materie.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="materie.xsd">
<materie>
<idmateria>M0000</idmateria>
<nomemateria>ALTERNATIVA</nomemateria>
<nomebrevemateria>ALTERNATIVA</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0001</idmateria>
<nomemateria>COMPLEMENTI MATEMATICA</nomemateria>
<nomebrevemateria>COMPLEMENTI MATEMATICA</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0002</idmateria>
<nomemateria>DIRITTO ed ECONOMIA</nomemateria>
<nomebrevemateria>DIRITTO ed ECONOMIA</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0003</idmateria>
<nomemateria>DISEGNO PROG. ORG. IND.</nomemateria>
<nomebrevemateria>DISEGNO PROG. ORG. IND.</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0004</idmateria>
<nomemateria>DISEGNO PROG. ORG. IND. LAB</nomemateria>
<nomebrevemateria>DISEGNO PROG. ORG. IND. LAB</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0005</idmateria>
<nomemateria>DISPO</nomemateria>
<nomebrevemateria>DISPO</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0006</idmateria>
<nomemateria>ELETTRON. ELETTROTEC.</nomemateria>
<nomebrevemateria>ELETTRON. ELETTROTEC.</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0007</idmateria>
<nomemateria>ELETTRON. ELETTROTEC. AUT.</nomemateria>
<nomebrevemateria>ELETTRON. ELETTROTEC. AUT.</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0008</idmateria>
<nomemateria>ELETTRON. ELETTROTEC. AUT. LAB</nomemateria>
<nomebrevemateria>ELETTRON. ELETTROTEC. AUT. LAB</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0009</idmateria>
<nomemateria>ELETTRON. ELETTROTEC. LAB</nomemateria>
<nomebrevemateria>ELETTRON. ELETTROTEC. LAB</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0010</idmateria>
<nomemateria>GEOGRAFIA</nomemateria>
<nomebrevemateria>GEOGRAFIA</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0011</idmateria>
<nomemateria>GESTIONE PR. ORG. IMPR.</nomemateria>
<nomebrevemateria>GESTIONE PR. ORG. IMPR.</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0012</idmateria>
<nomemateria>GESTIONE PR. ORG. IMPR. LAB</nomemateria>
<nomebrevemateria>GESTIONE PR. ORG. IMPR. LAB</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0013</idmateria>
<nomemateria>IMP. ENER. DISEG. PROG.</nomemateria>
<nomebrevemateria>IMP. ENER. DISEG. PROG.</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0014</idmateria>
<nomemateria>IMP. ENER. DISEG. PROG. LAB</nomemateria>
<nomebrevemateria>IMP. ENER. DISEG. PROG. LAB</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0015</idmateria>
<nomemateria>INFORMATICA</nomemateria>
<nomebrevemateria>INFORMATICA</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0016</idmateria>
<nomemateria>INFORMATICA LAB</nomemateria>
<nomebrevemateria>INFORMATICA LAB</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0017</idmateria>
<nomemateria>INGLESE</nomemateria>
<nomebrevemateria>INGLESE</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0018</idmateria>
<nomemateria>LING. E LETT. ITALIANA</nomemateria>
<nomebrevemateria>LING. E LETT. ITALIANA</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0019</idmateria>
<nomemateria>LOGISTICA</nomemateria>
<nomebrevemateria>LOGISTICA</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0020</idmateria>
<nomemateria>LOGISTICA LAB</nomemateria>
<nomebrevemateria>LOGISTICA LAB</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0021</idmateria>
<nomemateria>MATEMATICA</nomemateria>
<nomebrevemateria>MATEMATICA</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0022</idmateria>
<nomemateria>MECC. MACCH. ENERGIA</nomemateria>
<nomebrevemateria>MECC. MACCH. ENERGIA</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0023</idmateria>
<nomemateria>MECC. MACCH. ENERGIA LAB</nomemateria>
<nomebrevemateria>MECC. MACCH. ENERGIA LAB</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0024</idmateria>
<nomemateria>MECCANICA E MACCHINE</nomemateria>
<nomebrevemateria>MECCANICA E MACCHINE</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0025</idmateria>
<nomemateria>MECCANICA E MACCHINE LAB</nomemateria>
<nomebrevemateria>MECCANICA E MACCHINE LAB</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0026</idmateria>
<nomemateria>RECUPERO_ORARIO</nomemateria>
<nomebrevemateria>Nuova materia (1)</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0027</idmateria>
<nomemateria>RELIGIONE</nomemateria>
<nomebrevemateria>RELIGIONE</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0028</idmateria>
<nomemateria>RICEVIMENTO</nomemateria>
<nomebrevemateria>RICEVIMENTO</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0029</idmateria>
<nomemateria>SC. NAVIG. STRUTT. COST.</nomemateria>
<nomebrevemateria>SC. NAVIG. STRUTT. COST.</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0030</idmateria>
<nomemateria>SC. NAVIG. STRUTT. COST. LAB</nomemateria>
<nomebrevemateria>SC. NAVIG. STRUTT. COST. LAB</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0031</idmateria>
<nomemateria>SCIEN. TERRA/BIOLOGIA</nomemateria>
<nomebrevemateria>SCIEN. TERRA/BIOLOGIA</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0032</idmateria>
<nomemateria>SCIENZE INT. CHIMICA</nomemateria>
<nomebrevemateria>SCIENZE INT. CHIMICA</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0033</idmateria>
<nomemateria>SCIENZE INT. CHIMICA LAB</nomemateria>
<nomebrevemateria>SCIENZE INT. CHIMICA LAB</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0034</idmateria>
<nomemateria>SCIENZE INT. FISICA</nomemateria>
<nomebrevemateria>SCIENZE INT. FISICA</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0035</idmateria>
<nomemateria>SCIENZE INT. FISICA LAB</nomemateria>
<nomebrevemateria>SCIENZE INT. FISICA LAB</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0036</idmateria>
<nomemateria>SCIENZE MOTORIE</nomemateria>
<nomebrevemateria>SCIENZE MOTORIE</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0037</idmateria>
<nomemateria>SCIENZE TECNOL. APPL.</nomemateria>
<nomebrevemateria>SCIENZE TECNOL. APPL.</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0038</idmateria>
<nomemateria>SISTEMI AUTOMATICI</nomemateria>
<nomebrevemateria>SISTEMI AUTOMATICI</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0039</idmateria>
<nomemateria>SISTEMI AUTOMATICI LAB</nomemateria>
<nomebrevemateria>SISTEMI AUTOMATICI LAB</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0040</idmateria>
<nomemateria>SISTEMI E AUTOMAZIONE</nomemateria>
<nomebrevemateria>SISTEMI E AUTOMAZIONE</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0041</idmateria>
<nomemateria>SISTEMI E AUTOMAZIONE LAB</nomemateria>
<nomebrevemateria>SISTEMI E AUTOMAZIONE LAB</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0042</idmateria>
<nomemateria>SISTEMI E RETI</nomemateria>
<nomebrevemateria>SISTEMI E RETI</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0043</idmateria>
<nomemateria>SISTEMI E RETI LAB</nomemateria>
<nomebrevemateria>SISTEMI E RETI LAB</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0044</idmateria>
<nomemateria>sostegno</nomemateria>
<nomebrevemateria>sostegno</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0045</idmateria>
<nomemateria>STORIA CITT. E COSTIT.</nomemateria>
<nomebrevemateria>STORIA CITT. E COSTIT.</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0046</idmateria>
<nomemateria>studio assistito</nomemateria>
<nomebrevemateria>studio assistito</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0047</idmateria>
<nomemateria>TECN. INFORMAT.</nomemateria>
<nomebrevemateria>TECN. INFORMAT.</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0048</idmateria>
<nomemateria>TECN. INFORMAT. LAB</nomemateria>
<nomebrevemateria>TECN. INFORMAT. LAB</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0049</idmateria>
<nomemateria>TECN. MECC. PROG. PROD.</nomemateria>
<nomebrevemateria>TECN. MECC. PROG. PROD.</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0050</idmateria>
<nomemateria>TECN. MECC. PROG. PROD. LAB</nomemateria>
<nomebrevemateria>TECN. MECC. PROG. PROD. LAB</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0051</idmateria>
<nomemateria>TECN. PROG. SIST. E.E.</nomemateria>
<nomebrevemateria>TECN. PROG. SIST. E.E.</nomebrevemateria>
<codicemiur>(null)</codicemiur>
</materie>
<materie>
<idmateria>M0052</idmateria>
<nomemateria>TECN. PROG. SIST. E.E. LAB</nomemateria>
