=== PolpOnline/presenze-meucci/src/backend/src/fixtures/lessons/orario/Orario Provvisorio 5 ore  v5-XML/ore.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:choice maxOccurs="unbounded">
<xsd:element ref="ore"/>
</xsd:choice>
</xsd:complexType>
</xsd:element>
<xsd:element name="ore">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="idfoglio idgiorno idora" primary="yes" unique="yes" clustered="no"/>
<od:index index-name="idfoglio" index-key="idfoglio" primary="no" unique="no" clustered="no"/>
<od:index index-name="idgiorno" index-key="idgiorno" primary="no" unique="no" clustered="no"/>
<od:index index-name="idora" index-key="idora" primary="no" unique="no" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="idfoglio" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="idgiorno" minOccurs="0" od:jetType="longinteger" od:sqlSType="int">
<xsd:simpleType>
<xsd:restriction base="xsd:integer"/>
</xsd:simpleType>
</xsd:element>
<xsd:element name="idora" minOccurs="0" od:jetType="longinteger" od:sqlSType="int">
<xsd:simpleType>
<xsd:restriction base="xsd:integer"/>
</xsd:simpleType>
</xsd:element>
<xsd:element name="orainizio" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="5"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="orafine" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="5"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== PolpOnline/presenze-meucci/src/backend/src/fixtures/lessons/orario/Orario Provvisorio 5 ore  v5-XML/ore.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="ore.xsd">
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>0</idgiorno>
<idora>0</idora>
<orainizio>8.00</orainizio>
<orafine>8.50</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>0</idgiorno>
<idora>1</idora>
<orainizio>8.50</orainizio>
<orafine>9.50</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>0</idgiorno>
<idora>2</idora>
<orainizio>9.50</orainizio>
<orafine>10.45</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>0</idgiorno>
<idora>3</idora>
<orainizio>10.55</orainizio>
<orafine>11.50</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>0</idgiorno>
<idora>4</idora>
<orainizio>11.50</orainizio>
<orafine>12.45</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>0</idgiorno>
<idora>5</idora>
<orainizio>12.55</orainizio>
<orafine>13.50</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>0</idgiorno>
<idora>6</idora>
<orainizio>13.50</orainizio>
<orafine>14.40</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>1</idgiorno>
<idora>0</idora>
<orainizio>8.00</orainizio>
<orafine>8.50</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>1</idgiorno>
<idora>1</idora>
<orainizio>8.50</orainizio>
<orafine>9.50</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>1</idgiorno>
<idora>2</idora>
<orainizio>9.50</orainizio>
<orafine>10.45</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>1</idgiorno>
<idora>3</idora>
<orainizio>10.55</orainizio>
<orafine>11.50</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>1</idgiorno>
<idora>4</idora>
<orainizio>11.50</orainizio>
<orafine>12.45</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>1</idgiorno>
<idora>5</idora>
<orainizio>12.55</orainizio>
<orafine>13.50</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>1</idgiorno>
<idora>6</idora>
<orainizio>13.50</orainizio>
<orafine>14.40</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>2</idgiorno>
<idora>0</idora>
<orainizio>8.00</orainizio>
<orafine>8.50</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>2</idgiorno>
<idora>1</idora>
<orainizio>8.50</orainizio>
<orafine>9.50</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>2</idgiorno>
<idora>2</idora>
<orainizio>9.50</orainizio>
<orafine>10.45</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>2</idgiorno>
<idora>3</idora>
<orainizio>10.55</orainizio>
<orafine>11.50</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>2</idgiorno>
<idora>4</idora>
<orainizio>11.50</orainizio>
<orafine>12.45</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>2</idgiorno>
<idora>5</idora>
<orainizio>12.55</orainizio>
<orafine>13.50</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>2</idgiorno>
<idora>6</idora>
<orainizio>13.50</orainizio>
<orafine>14.40</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>3</idgiorno>
<idora>0</idora>
<orainizio>8.00</orainizio>
<orafine>8.50</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>3</idgiorno>
<idora>1</idora>
<orainizio>8.50</orainizio>
<orafine>9.50</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>3</idgiorno>
<idora>2</idora>
<orainizio>9.50</orainizio>
<orafine>10.45</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>3</idgiorno>
<idora>3</idora>
<orainizio>10.55</orainizio>
<orafine>11.50</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>3</idgiorno>
<idora>4</idora>
<orainizio>11.50</orainizio>
<orafine>12.45</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>3</idgiorno>
<idora>5</idora>
<orainizio>12.55</orainizio>
<orafine>13.50</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>3</idgiorno>
<idora>6</idora>
<orainizio>13.50</orainizio>
<orafine>14.40</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>4</idgiorno>
<idora>0</idora>
<orainizio>8.00</orainizio>
<orafine>8.50</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>4</idgiorno>
<idora>1</idora>
<orainizio>8.50</orainizio>
<orafine>9.50</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>4</idgiorno>
<idora>2</idora>
<orainizio>9.50</orainizio>
<orafine>10.45</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>4</idgiorno>
<idora>3</idora>
<orainizio>10.55</orainizio>
<orafine>11.50</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>4</idgiorno>
<idora>4</idora>
<orainizio>11.50</orainizio>
<orafine>12.45</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>4</idgiorno>
<idora>5</idora>
<orainizio>12.55</orainizio>
<orafine>13.50</orafine>
</ore>
<ore>
<idfoglio>F0000</idfoglio>
<idgiorno>4</idgiorno>
<idora>6</idora>
<orainizio>13.50</orainizio>
<orafine>14.40</orafine>
</ore>
</dataroot>
