=== PolpOnline/presenze-meucci/src/backend/src/fixtures/lessons/orario/Orario Provvisorio 5 ore  v5-XML/sedi.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:choice maxOccurs="unbounded">
<xsd:element ref="sedi"/>
</xsd:choice>
</xsd:complexType>
</xsd:element>
<xsd:element name="sedi">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="idsede" index-key="idsede" primary="yes" unique="yes" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="idsede" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="nomesede" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="nomebrevesede" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== PolpOnline/presenze-meucci/src/backend/src/fixtures/lessons/orario/Orario Provvisorio 5 ore  v5-XML/sedi.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="sedi.xsd">
<sedi>
<idsede>S0000</idsede>
<nomesede>Meccanica</nomesede>
<nomebrevesede>Meccanica</nomebrevesede>
</sedi>
<sedi>
<idsede>S0001</idsede>
<nomesede>Prefabbricato</nomesede>
<nomebrevesede>Prefabbricato</nomebrevesede>
</sedi>
<sedi>
<idsede>S0002</idsede>
<nomesede>Sede</nomesede>
<nomebrevesede>Sede</nomebrevesede>
</sedi>
</dataroot>
